[package]
name = "three-dimensional-model-simulation"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cgmath = "0.18.0"
glium = "0.32.1"
gltf = "1.1.0"
obj-rs = "0.7.0"
